"""
app.services.config_compiler
==============================
This is the component spec section 13 calls "one of the most important
architectural components": it turns PostgreSQL state into a candidate
tac_plus-ng configuration, validates it, computes a diff against
what's actually live on disk, and -- only on explicit confirmation --
backs up, applies, reloads, health-checks, and auto-rolls-back on
failure (sections 14-15, 34).

NOTE ON DUPLICATION: the static preamble (spawnd block + log targets)
below is intentionally kept textually identical to
installer/bootstrap_config.py's template. That installer module runs
at install time, before this application package is even copied to
/opt/aaa-platform, so the two can't share a live import -- see
docs/ARCHITECTURE.md for why they're two files, not one.
"""
from __future__ import annotations

import difflib
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import func
from sqlalchemy.orm import Session

from .. import security
from ..config import BACKUPS_DIR, GENERATED_DIR, LOG_DIR
from ..models.config_version import ConfigVersion
from ..models.device import NetworkDevice
from ..models.group import TacacsGroup
from ..models.policy import Policy
from ..models.policy_condition import PolicyCondition
from ..models.policy_condition_group import PolicyConditionGroup
from ..models.system_info import InstallEvent
from ..models.user import TacacsUser
from . import build_info_service, condition_engine, policy_engine, service_control

ACTIVE_CONFIG_PATH = GENERATED_DIR / "tac_plus-ng.conf"

# Field separator for the accounting log format string below. A
# literal, self-chosen delimiter rather than the ${FS} built-in
# variable: ${FS}'s own configurability was not independently
# confirmed (a "log separator = ..." directive was seen in one
# community example but not confirmed for tac_plus-ng specifically),
# so writing our own delimiter directly into the format string
# sidesteps that uncertainty entirely rather than depending on it.
# "::" was chosen for being vanishingly unlikely to appear inside a
# real device name, username, or command line -- app.services.
# accounting_log.py's parser splits on this same constant, so the two
# sides can never drift out of sync with each other.
ACCOUNTING_FIELD_SEPARATOR = "::"

STATIC_PREAMBLE = """\
# Generated by the AAA Management Platform configuration compiler.
# DO NOT hand-edit: changes made directly to this file will be
# overwritten on the next Apply and are not tracked in configuration
# history. Manage devices through the Web GUI or REST API instead.

id = spawnd {{
    background = no
    listen = {{ port = {tacacs_port} }}
    spawn = {{
        instances min = 1
        instances max = 10
    }}
}}

id = tac_plus-ng {{
    log accesslog {{ destination = {log_dir}/tac_plus-ng-access.log }}
    log authorlog {{ destination = {log_dir}/tac_plus-ng-authorization.log }}
    log acctlog {{
        destination = {log_dir}/tac_plus-ng-accounting.log
        accounting format = "${{nas}}{fs}${{user}}{fs}${{port}}{fs}${{nac}}{fs}${{accttype}}{fs}${{result}}{fs}${{service}}{fs}${{cmd}}"
    }}

    access log = accesslog
    authorization log = authorlog
    accounting log = acctlog

{host_blocks}\
{group_blocks}\
{user_blocks}\
{acl_blocks}\
{policy_blocks}\
{ruleset_block}\
}}
"""


class ConfigCompilerError(RuntimeError):
    pass


class UncompilablePolicyError(RuntimeError):
    """
    Raised when a policy's condition tree contains something with no
    confirmed tac_plus-ng syntax to compile it into -- per the pasted
    condition-builder spec's explicit "if something cannot be
    represented safely in tac_plus-ng, do NOT fake it" instruction.
    The caller (compile_candidate) catches this PER POLICY and
    excludes just that one policy from the generated ruleset entirely
    -- it simply never matches anything in the compiled config, which
    is the safe, deny-leaning failure mode this project has used
    consistently since Phase 5, not a silently-wrong or partially-fake
    compilation. compile_candidate() also records an InstallEvent for
    every exclusion, so this is auditable, not a silent gap.
    """
    pass


class ApplyFailedError(RuntimeError):
    def __init__(self, message: str, journal: str = ""):
        super().__init__(message)
        self.journal = journal


def _quote(value: str) -> str:
    """Double-quote a config value, escaping backslashes and quotes.
    Used only for values (shared secrets); device *names* are never
    passed through this -- see app.schemas.device for why identifiers
    are restricted at input time instead of escaped."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _host_block(device: NetworkDevice) -> str:
    secret = security.decrypt_secret(device.shared_secret_encrypted)
    lines = [f"    host {device.name} {{"]
    lines.append(f"        address = {device.ip_address}")
    if device.ipv6_address:
        # NOT emitted as a directive: no IPv6-specific `host` block
        # syntax (e.g. a hypothetical `address6 =`) was confirmed
        # against upstream docs/samples during research, and inventing
        # one here would be exactly the "policy that doesn't translate
        # correctly to the core" spec section 20 warns against. The
        # value is still stored and shown in the GUI so it's not lost,
        # and surfaced as a comment so it's visible to anyone reading
        # the generated file, pending confirmation of real syntax.
        lines.append(f"        # ipv6_address on file (not yet emitted, syntax unconfirmed): {device.ipv6_address}")
    lines.append(f"        key = {_quote(secret)}")
    lines.append("    }")
    return "\n".join(lines) + "\n"


def _user_block(user: TacacsUser, group_name: str | None) -> str:
    """
    Syntax confirmed against a real, working tac_plus-ng configuration
    (not legacy tac_plus, which uses different, incompatible
    directives -- `login = des <hash>` there vs `password login =
    crypt <hash>` here) posted by a user on the project's own support
    forum, with the maintainer replying in the same thread without
    correcting the syntax. `crypt` expects a standard libc crypt()
    hash; bcrypt's `$2b$`/`$2y$`-prefixed output (what
    app.security.hash_password already produces for platform admins)
    is a standard crypt() format, and Ubuntu's default libcrypt
    (libxcrypt since 20.04) supports verifying it. This was confirmed
    end-to-end against a real installation in Phase 3.

    `member = <group>` (Phase 4) uses the exact same confirmed sample
    (`user test1 { password login = clear secret member = admins }`).
    Only ever emitted when the user actually has a group -- Phase 5's
    authorization engine is what gives group membership real teeth via
    `if (member == ...)` in ruleset scripts, but the membership itself
    is real, generated config today, not a placeholder.

    The hash is emitted unquoted, matching the real-world example this
    was confirmed against. This is safe, not just convenient: crypt()
    hash output (including bcrypt) only ever uses the fixed alphabet
    `./0-9A-Za-z` plus `$` as a field separator -- never `{`, `}`,
    `"`, `#`, or whitespace -- so there's no config-injection surface
    here the way there would be for an arbitrary user-supplied string.
    """
    lines = [f"    user {user.username} {{"]
    lines.append(f"        password login = crypt {user.password_hash}")
    if group_name:
        lines.append(f"        member = {group_name}")
    lines.append("    }")
    return "\n".join(lines) + "\n"


def _group_block(group: TacacsGroup) -> str:
    """
    Confirmed valid as an EMPTY block against the same real-world
    sample (`group admins { }`, `group ad-admins { }` both appeared
    with no body). Actual permission content lives in Phase 5's
    `profile {}`/`ruleset {}` blocks, which reference group membership
    via `if (member == <group>)` -- the group itself is just the named
    bucket users get sorted into.
    """
    return f"    group {group.name} {{\n    }}\n"


def _policy_block(policy: Policy, ordered_rules: list) -> str:
    """
    Confirmed against FOUR independent real tac_plus-ng configs (see
    app/models/policy.py): the outer structure --

        profile <name> {
            script {
                if (service == shell) {
                    if (cmd == "") {
                        set priv-lvl = <N>
                    }
                    permit-or-deny-statements...
                }
            }
        }

    -- is real, working syntax. What's NOT independently confirmed the
    same way is matching a SPECIFIC command name via `cmd =~
    /pattern/` for the CommandRule entries below (see
    app/models/command_rule.py's docstring for exactly what is and
    isn't verified here).

    `ordered_rules` is expected pre-flattened and deny-first ordered
    by app.services.policy_engine.get_ordered_rules_for_policy --
    this function no longer does that ordering itself (PAM Expansion
    Plan Increment 1: rules now come from every CommandSet the policy
    references, not one owned list), specifically so the compiler and
    the Simulator/Effective-Access engine can never independently
    drift on what "deny-first" means. The policy's own default_action
    is the trailing, unconditional fallback for anything no rule
    matched.
    """
    lines = [f"    profile {policy.name} {{"]
    lines.append("        script {")
    lines.append("            if (service == shell) {")
    lines.append("                if (cmd == \"\") {")
    lines.append(f"                    set priv-lvl = {policy.default_priv_lvl}")
    lines.append("                }")

    for rule in ordered_rules:
        # command_pattern is validated as a real regex at input time
        # (app.schemas.command_set) but is otherwise arbitrary admin-
        # supplied text -- unlike identifiers, it legitimately needs
        # to contain regex metacharacters, so it's placed inside a
        # PCRE delimiter (/.../ ) rather than restricted to a safe
        # charset. It is NOT interpolated into anything that could
        # break out of the surrounding script block: tac_plus-ng's own
        # regex delimiter is what bounds it, the same way _quote()
        # bounds shared secrets with double quotes elsewhere in this
        # file.
        lines.append(f"                if (cmd =~ /{rule.command_pattern}/) {{ {rule.action} }}")
    lines.append(f"                {policy.default_action}")
    lines.append("            }")
    lines.append("        }")
    lines.append("    }")
    return "\n".join(lines) + "\n"


def _condition_expression(
    policy: Policy,
    *,
    group_names_by_id: dict,
    device_names_by_id: dict,
    device_names_by_group_id: dict,
) -> str | None:
    """
    LEGACY model only (see resolve_condition_expression below for the
    dispatch between this and the new condition-tree compiler).
    Translates a Policy's condition_* fields (PAM Expansion Plan §4)
    into a tac_plus-ng script boolean expression, combining multiple
    conditions on the same policy with `&&`. Returns None when the
    policy has no conditions at all -- such a policy matches
    unconditionally (see _ruleset_block for how that's emitted, since
    an unconditional rule needs no `if` wrapper at all).

    `member == <group>` and `device == <hostname>` are both confirmed
    real syntax (see app/models/policy.py's docstring for sources).
    Device-GROUP targeting has no native tac_plus-ng concept (same
    finding as Phase 4's Device Groups), so it's expanded here into a
    generated OR-chain of individual `device == ...` checks -- real
    syntax, generated rather than native, exactly as planned.
    """
    clauses = []

    if policy.condition_group_id is not None:
        group_name = group_names_by_id.get(policy.condition_group_id)
        if group_name:
            clauses.append(f"member == {group_name}")

    if policy.condition_device_id is not None:
        device_name = device_names_by_id.get(policy.condition_device_id)
        if device_name:
            clauses.append(f"device == {device_name}")

    if policy.condition_device_group_id is not None:
        member_device_names = device_names_by_group_id.get(policy.condition_device_group_id, [])
        if member_device_names:
            or_chain = " || ".join(f"device == {name}" for name in member_device_names)
            clauses.append(f"({or_chain})" if len(member_device_names) > 1 else or_chain)

    if not clauses:
        return None
    return " && ".join(clauses)


def _compile_condition_leaf(
    condition: PolicyCondition,
    *,
    group_names_by_id: dict,
    device_names_by_id: dict,
    device_names_by_group_id: dict,
    acl_blocks_out: list[str],
) -> str:
    """
    Compiles ONE condition-tree leaf into real tac_plus-ng syntax, or
    raises UncompilablePolicyError. Confidence per construct (see
    docs/ARCHITECTURE.md for the sourcing):

    - `member == <name>` / `device == <name>` -- CONFIRMED (same
      sources as the legacy _condition_expression above).
    - `member != <name>` / `device != <name>` / `nac != <name>` --
      REASONED, not directly observed for these specific comparisons:
      a real event-driven-servers mailing-list thread confirms tac_plus
      -ng accepts `!=` for ACL comparisons generally (a parser bug that
      had blocked it was explicitly fixed), and every `if()` expression
      in this scripting language shares one grammar (the same thread's
      own example combines an ACL check and a `member ==` check with
      `&&` in a single expression) -- so `!=` extending to member/device
      comparisons the same way `==` already does is a reasoned
      extension of confirmed behavior, not a guess from nothing.
    - `nac == <cidr>` inside an `acl { }` block, referenced via
      `acl == <name>` -- CONFIRMED directly: a real example
      (`acl alu_tl_mbh { if (nac == 10.27.64.0/21) permit deny }`,
      referenced as `if (acl == alu_tl_mbh && member == region)`)
      shows exactly this CIDR-range-via-== pattern working inside an
      ACL block specifically. is_not_in_cidr negates at the REFERENCE
      point (`acl != <name>`) rather than guessing at a differently
      -negated internal ACL check that hasn't been directly observed,
      to stay as close as possible to the one confirmed example.
    - Direct per-user matching (`user` object type, any operator) --
      NOT compilable. Every confirmed real tac_plus-ng example matches
      via `member == <group>`, never a bare username.
    """
    obj_type = condition.object_type
    op = condition.operator

    if obj_type == "user":
        raise UncompilablePolicyError(
            "Direct per-user conditions have no confirmed tac_plus-ng syntax and cannot be compiled -- "
            "target the user's group instead."
        )

    elif obj_type == "user_group":
        name = group_names_by_id.get(condition.referenced_object_id)
        if not name:
            raise UncompilablePolicyError("This condition's referenced user group no longer exists.")
        if op == "equal":
            return f"member == {name}"
        elif op == "not_equal":
            return f"member != {name}"
        raise UncompilablePolicyError(f"Operator '{op}' is not compilable for user_group.")

    elif obj_type == "device":
        name = device_names_by_id.get(condition.referenced_object_id)
        if not name:
            raise UncompilablePolicyError("This condition's referenced device no longer exists.")
        if op == "equal":
            return f"device == {name}"
        elif op == "not_equal":
            return f"device != {name}"
        raise UncompilablePolicyError(f"Operator '{op}' is not compilable for device.")

    elif obj_type == "device_group":
        member_names = device_names_by_group_id.get(condition.referenced_object_id, [])
        if not member_names:
            raise UncompilablePolicyError("This condition's referenced device group has no members, or no longer exists.")
        if op == "equal":
            or_chain = " || ".join(f"device == {n}" for n in member_names)
            return f"({or_chain})" if len(member_names) > 1 else or_chain
        elif op == "not_equal":
            and_chain = " && ".join(f"device != {n}" for n in member_names)
            return f"({and_chain})" if len(member_names) > 1 else and_chain
        raise UncompilablePolicyError(f"Operator '{op}' is not compilable for device_group.")

    elif obj_type == "source_ip":
        if op == "equal":
            return f"nac == {condition.value}"
        elif op == "not_equal":
            return f"nac != {condition.value}"
        elif op in ("is_in_cidr", "is_not_in_cidr"):
            acl_name = f"acl_cond_{str(condition.id).replace('-', '')[:12]}"
            acl_blocks_out.append(f"    acl {acl_name} {{ if (nac == {condition.value}) permit deny }}\n")
            reference_op = "==" if op == "is_in_cidr" else "!="
            return f"acl {reference_op} {acl_name}"
        raise UncompilablePolicyError(f"Operator '{op}' is not compilable for source_ip.")

    raise UncompilablePolicyError(f"Unknown condition object type '{obj_type}'.")


def _compile_condition_group_tree(
    db: Session,
    group: PolicyConditionGroup,
    *,
    group_names_by_id: dict,
    device_names_by_id: dict,
    device_names_by_group_id: dict,
    acl_blocks_out: list[str],
) -> str:
    """
    Recursively compiles a condition-tree group into a tac_plus-ng
    boolean expression. AND -> `&&`, OR -> `||` (both confirmed --
    already used by the legacy compiler and the official upstream
    sample's own multi-condition rules). NOT is NOT yet compilable:
    `!` has no confirmed tac_plus-ng syntax the way `&&`/`||`/`==`/`!=`
    now do -- a NOT group anywhere in the tree makes the WHOLE policy
    uncompilable (see UncompilablePolicyError's docstring for what
    that means in practice: excluded from the ruleset, not faked).
    """
    child_conditions = (
        db.query(PolicyCondition).filter(PolicyCondition.group_id == group.id).order_by(PolicyCondition.order.asc()).all()
    )
    child_groups = (
        db.query(PolicyConditionGroup)
        .filter(PolicyConditionGroup.parent_group_id == group.id)
        .order_by(PolicyConditionGroup.order.asc())
        .all()
    )

    clauses = []
    for cond in child_conditions:
        clauses.append(_compile_condition_leaf(
            cond,
            group_names_by_id=group_names_by_id,
            device_names_by_id=device_names_by_id,
            device_names_by_group_id=device_names_by_group_id,
            acl_blocks_out=acl_blocks_out,
        ))
    for child_group in child_groups:
        sub_expr = _compile_condition_group_tree(
            db, child_group,
            group_names_by_id=group_names_by_id,
            device_names_by_id=device_names_by_id,
            device_names_by_group_id=device_names_by_group_id,
            acl_blocks_out=acl_blocks_out,
        )
        clauses.append(f"({sub_expr})")

    if not clauses:
        raise UncompilablePolicyError("An empty condition group cannot be compiled.")

    if group.logical_operator == "AND":
        return " && ".join(clauses)
    elif group.logical_operator == "OR":
        return " || ".join(clauses)
    elif group.logical_operator == "NOT":
        raise UncompilablePolicyError(
            "NOT groups have no confirmed tac_plus-ng syntax ('!' has not been confirmed) and cannot be compiled yet."
        )
    raise UncompilablePolicyError(f"Unknown logical operator '{group.logical_operator}'.")


def resolve_condition_expression(
    db: Session,
    policy: Policy,
    *,
    group_names_by_id: dict,
    device_names_by_id: dict,
    device_names_by_group_id: dict,
    acl_blocks_out: list[str],
) -> str | None:
    """
    The single dispatch point between the legacy flat-field model and
    the new condition-tree model for compilation -- the SAME switch
    app.services.policy_engine.evaluate() uses for evaluation
    (condition_engine.has_condition_tree()), so a policy is compiled
    using the identical model it's evaluated/simulated under; the two
    can never diverge on which model a given policy is using. Can
    raise UncompilablePolicyError for a tree-model policy -- the
    caller (compile_candidate) must catch this per policy.
    """
    if condition_engine.has_condition_tree(db, policy):
        root = condition_engine.get_root_group(db, policy)
        if root is None:
            raise UncompilablePolicyError("This policy's condition tree is missing its root group.")
        return _compile_condition_group_tree(
            db, root,
            group_names_by_id=group_names_by_id,
            device_names_by_id=device_names_by_id,
            device_names_by_group_id=device_names_by_group_id,
            acl_blocks_out=acl_blocks_out,
        )
    return _condition_expression(
        policy,
        group_names_by_id=group_names_by_id,
        device_names_by_id=device_names_by_id,
        device_names_by_group_id=device_names_by_group_id,
    )


def _ruleset_block(policies_with_conditions: list[tuple[Policy, str | None]]) -> str:
    """
    Confirmed against the official upstream sample config
    (tac_plus-ng/sample/tac_plus-ng.cfg): a single top-level `ruleset
    {}` block containing one named `rule <name> { }` per policy, each
    with its own `script`. `policies_with_conditions` must already be
    in the exact order evaluation should walk them (see
    app.services.policy_engine.get_ordered_policies) and already
    exclude any policy resolve_condition_expression() couldn't compile
    -- this function only renders, it doesn't decide what's compilable.

    A policy with no conditions (condition is None) matches
    unconditionally -- its rule's script body is a bare `profile =
    <name> permit` with no `if` wrapper, rather than something
    artificial like `if (1)`, since a bare statement is the more
    directly defensible translation of "always applies" into this
    scripting language.
    """
    if not policies_with_conditions:
        return ""

    lines = ["    ruleset {"]
    for policy, condition in policies_with_conditions:
        lines.append(f"        rule {policy.name} {{")
        lines.append("            enabled = yes")
        lines.append("            script {")
        if condition:
            lines.append(f"                if ({condition}) {{")
            lines.append(f"                    profile = {policy.name}")
            lines.append("                    permit")
            lines.append("                }")
        else:
            lines.append(f"                profile = {policy.name}")
            lines.append("                permit")
        lines.append("            }")
        lines.append("        }")
    lines.append("    }")
    return "\n".join(lines) + "\n"


def get_uncompilable_policies(db: Session) -> list[tuple[Policy, str]]:
    """
    Read-only check: which enabled policies would be excluded from
    the ruleset if compiled right now, and why. Shares the exact same
    resolve_condition_expression() logic compile_candidate() uses
    internally, so this can never disagree with what actually gets
    excluded. Exists as its own callable (rather than folded silently
    into compile_candidate(), which is documented and relied upon as
    a pure function with no side effects) specifically so callers that
    DO want to act on this -- apply_candidate() recording an
    InstallEvent, or a future Diagnostics page warning -- can, without
    every plain candidate-preview call (the GET /candidate endpoint,
    the Simulator, diagnostics' "would_change" check) picking up an
    unexpected write.
    """
    groups = db.query(TacacsGroup).all()
    group_names_by_id = {g.id: g.name for g in groups}
    all_devices = db.query(NetworkDevice).all()
    device_names_by_id = {d.id: d.name for d in all_devices}
    device_names_by_group_id: dict = {}
    for d in all_devices:
        if d.device_group_id is not None:
            device_names_by_group_id.setdefault(d.device_group_id, []).append(d.name)

    excluded = []
    for policy in policy_engine.get_ordered_policies(db):
        try:
            resolve_condition_expression(
                db, policy,
                group_names_by_id=group_names_by_id,
                device_names_by_id=device_names_by_id,
                device_names_by_group_id=device_names_by_group_id,
                acl_blocks_out=[],  # discarded -- this call is for the exclusion check only
            )
        except UncompilablePolicyError as exc:
            excluded.append((policy, str(exc)))
    return excluded


def compile_candidate(db: Session) -> str:
    """Pure function of DB state: same devices/users/groups/policies
    in, same config text out, every time -- which is what makes
    diffing meaningful. A policy whose condition tree can't be safely
    compiled (see resolve_condition_expression / UncompilablePolicyError)
    is silently excluded from the OUTPUT here -- "silently" only in the
    sense that this function itself never writes anything (it's pure);
    see get_uncompilable_policies() for how a caller gets visibility
    into exactly which policies and why, and apply_candidate() below
    for where that visibility becomes an actual recorded InstallEvent."""
    devices = (
        db.query(NetworkDevice)
        .filter(NetworkDevice.enabled.is_(True))
        .order_by(NetworkDevice.name.asc())
        .all()
    )
    users = (
        db.query(TacacsUser)
        .filter(TacacsUser.enabled.is_(True))
        .order_by(TacacsUser.username.asc())
        .all()
    )
    groups = db.query(TacacsGroup).order_by(TacacsGroup.name.asc()).all()
    group_names_by_id = {g.id: g.name for g in groups}

    # ALL devices (not just enabled ones) for resolving policy
    # condition names -- a policy condition referencing a currently
    # disabled device should still resolve to that device's real name
    # (a harmless, inert reference, since no host block exists for it
    # while disabled) rather than silently vanish and make the whole
    # policy unconditional just because one condition failed to
    # resolve.
    all_devices = db.query(NetworkDevice).all()
    device_names_by_id = {d.id: d.name for d in all_devices}
    device_names_by_group_id: dict = {}
    for d in all_devices:
        if d.device_group_id is not None:
            device_names_by_group_id.setdefault(d.device_group_id, []).append(d.name)

    all_policies = policy_engine.get_ordered_policies(db)

    acl_blocks_out: list[str] = []
    compilable_policies: list[tuple[Policy, str | None]] = []
    for policy in all_policies:
        try:
            condition = resolve_condition_expression(
                db, policy,
                group_names_by_id=group_names_by_id,
                device_names_by_id=device_names_by_id,
                device_names_by_group_id=device_names_by_group_id,
                acl_blocks_out=acl_blocks_out,
            )
        except UncompilablePolicyError:
            continue  # excluded -- see get_uncompilable_policies() for why, callers that need to know check that separately
        compilable_policies.append((policy, condition))

    host_blocks = "".join(_host_block(d) for d in devices)
    group_blocks = "".join(_group_block(g) for g in groups)
    user_blocks = "".join(_user_block(u, group_names_by_id.get(u.group_id)) for u in users)
    policy_blocks = "".join(
        _policy_block(p, policy_engine.get_ordered_rules_for_policy(db, p)) for p, _ in compilable_policies
    )
    acl_blocks = "".join(acl_blocks_out)
    ruleset_block = _ruleset_block(compilable_policies)

    from ..platform_settings import load_settings
    tacacs_port = load_settings()["tacacs_port"]

    return STATIC_PREAMBLE.format(
        log_dir=LOG_DIR,
        fs=ACCOUNTING_FIELD_SEPARATOR,
        tacacs_port=tacacs_port,
        host_blocks=host_blocks,
        group_blocks=group_blocks,
        user_blocks=user_blocks,
        acl_blocks=acl_blocks,
        policy_blocks=policy_blocks,
        ruleset_block=ruleset_block,
    )


def get_active_config() -> str:
    """Reads whatever is actually deployed on disk right now -- not the
    database's idea of the last-applied version -- so a diff is always
    accurate even if Phase 1's bootstrap file was never run through
    this compiler, or if someone hand-edited the live file against the
    header's advice not to."""
    if not ACTIVE_CONFIG_PATH.exists():
        return ""
    return ACTIVE_CONFIG_PATH.read_text(encoding="utf-8")


def compute_diff(active: str, candidate: str) -> str:
    diff_lines = difflib.unified_diff(
        active.splitlines(keepends=True),
        candidate.splitlines(keepends=True),
        fromfile="active (deployed)",
        tofile="candidate (pending)",
    )
    return "".join(diff_lines)


def _binary_path() -> str | None:
    info = build_info_service.get_build_info()
    return info.get("binary_path")


@dataclass
class ValidationResult:
    validated: bool          # True only on a clean exit (returncode == 0)
    output: str
    definitively_failed: bool  # see validate_candidate()'s docstring


# Substrings the daemon itself uses for an unambiguous fatal parse
# error -- confirmed against real output from a live install
# ("34079: Detected fatal configuration error. Exiting." /
# "log variable 'task_id' is not recognized"), not assumed. Matched
# case-insensitively against the combined stdout+stderr.
_DEFINITIVE_FAILURE_MARKERS = (
    "fatal configuration error",
    "is not recognized",
)


def validate_candidate(candidate_text: str) -> ValidationResult:
    """
    Syntax check via the binary's own `-P` flag (documented for legacy
    tac_plus as "parse config and exit"; not independently confirmed
    for tac_plus-ng in the abstract -- see installer/bootstrap_config.py
    -- but its RELIABILITY is now confirmed by a real deployment: a
    real invalid config (`${task_id}` in the accounting format, since
    removed -- see app/services/accounting_log.py's correction note)
    was caught here with a clear, parseable error message, exactly as
    intended.

    A non-zero exit is only escalated to `definitively_failed=True`
    when the daemon's own output contains one of
    `_DEFINITIVE_FAILURE_MARKERS` -- an unambiguous, human-readable
    statement that parsing failed, not just an unexplained nonzero
    exit code (which could have other causes -- binary not found,
    permissions, timeout -- that don't mean the config text itself is
    bad). `apply_candidate()` below now BLOCKS on
    `definitively_failed`, per the same real-world evidence: -P
    reliably reports fatal errors clearly, so trusting a clear failure
    message enough to block on it is now justified, not merely
    convenient. A non-zero exit WITHOUT a matched marker still doesn't
    block -- that's the genuinely ambiguous case the original,
    more cautious design was written for, and the post-reload health
    check in apply_candidate() remains the backstop for it.
    """
    binary = _binary_path()
    if not binary:
        return ValidationResult(False, "tac_plus-ng binary path unknown (build_info.json missing/incomplete).", False)

    import tempfile
    with tempfile.NamedTemporaryFile("w", suffix=".conf", delete=False) as tmp:
        tmp.write(candidate_text)
        tmp_path = tmp.name

    try:
        result = subprocess.run(
            [binary, "-P", tmp_path], capture_output=True, text=True, timeout=15
        )
        output = (result.stdout + result.stderr).strip()
        validated = result.returncode == 0
        definitively_failed = (not validated) and any(
            marker in output.lower() for marker in _DEFINITIVE_FAILURE_MARKERS
        )
        return ValidationResult(validated, output, definitively_failed)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return ValidationResult(False, f"Could not run validation: {exc}", False)
    finally:
        Path(tmp_path).unlink(missing_ok=True)


def _next_version_number(db: Session) -> int:
    current_max = db.query(func.max(ConfigVersion.version_number)).scalar()
    return (current_max or 0) + 1


def _backup_active(version_number: int) -> Path | None:
    if not ACTIVE_CONFIG_PATH.exists():
        return None
    BACKUPS_DIR.mkdir(parents=True, exist_ok=True)
    backup_path = BACKUPS_DIR / f"tac_plus-ng.conf.v{version_number - 1}.bak"
    backup_path.write_text(ACTIVE_CONFIG_PATH.read_text(encoding="utf-8"), encoding="utf-8")
    return backup_path


def apply_candidate(
    db: Session,
    *,
    candidate_text: str,
    admin_username: str,
    note: str | None = None,
    status: str = "applied",
) -> ConfigVersion:
    """
    The full section 14 workflow: backup -> write -> reload ->
    health-check -> (auto-rollback on failure). Raises ApplyFailedError
    if the daemon doesn't come back healthy, after restoring the prior
    config and reloading again.
    """
    previous_active = get_active_config()
    version_number = _next_version_number(db)

    validation = validate_candidate(candidate_text)
    if validation.definitively_failed:
        # Confirmed by real deployment evidence (see validate_candidate's
        # docstring): the daemon's own fatal-error output is trustworthy
        # enough to block on outright, rather than writing a known-bad
        # config to disk and reloading the live daemon to find out --
        # which would cause a real, if brief, outage before the
        # post-reload health check below could catch and roll it back.
        db.add(InstallEvent(
            event_type="config_validation_failed",
            detail=validation.output[:2000],
        ))
        db.commit()
        raise ApplyFailedError(
            "The generated configuration failed tac_plus-ng's own syntax "
            f"check and was NOT applied -- nothing on the live daemon was "
            f"touched:\n\n{validation.output}"
        )
    if not validation.validated:
        db.add(InstallEvent(
            event_type="config_validation_inconclusive",
            detail=validation.output[:2000],
        ))
        db.commit()

    _backup_active(version_number)

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    ACTIVE_CONFIG_PATH.write_text(candidate_text, encoding="utf-8")

    try:
        service_control.reload(service_control.TAC_PLUS_NG_UNIT)
    except service_control.ServiceControlError:
        # `reload` can fail outright (e.g. unit not currently running) --
        # fall back to a full restart before giving up.
        try:
            service_control.restart(service_control.TAC_PLUS_NG_UNIT)
        except service_control.ServiceControlError as exc:
            _rollback(db, previous_active, reason=str(exc))
            raise ApplyFailedError(f"Could not reload or restart tac_plus-ng: {exc}") from exc

    import time
    time.sleep(2)
    live_status = service_control.get_status(service_control.TAC_PLUS_NG_UNIT)

    if live_status.active_state != "active":
        journal = service_control.recent_logs(service_control.TAC_PLUS_NG_UNIT)
        _rollback(db, previous_active, reason=f"service state after reload: {live_status.active_state}")
        raise ApplyFailedError(
            "tac_plus-ng did not stay active after applying the new configuration. "
            "The previous known-good configuration has been restored automatically.",
            journal=journal,
        )

    version = ConfigVersion(
        version_number=version_number,
        content=candidate_text,
        status=status,
        created_by=admin_username,
        note=note,
    )
    db.add(version)
    db.add(InstallEvent(
        event_type="config_apply_succeeded",
        detail=f"Applied version {version_number} by {admin_username}.",
    ))
    db.commit()
    db.refresh(version)
    return version


def _rollback(db: Session, previous_content: str, *, reason: str) -> None:
    ACTIVE_CONFIG_PATH.write_text(previous_content, encoding="utf-8")
    try:
        service_control.reload(service_control.TAC_PLUS_NG_UNIT)
    except service_control.ServiceControlError:
        try:
            service_control.restart(service_control.TAC_PLUS_NG_UNIT)
        except service_control.ServiceControlError:
            pass  # Surfaced to the admin via the ApplyFailedError already raised by the caller.
    try:
        db.add(InstallEvent(event_type="config_auto_rollback", detail=reason[:2000]))
        db.commit()
    except Exception:
        db.rollback()
