"""
app.services.policy_engine
============================
PAM Expansion Plan §4's "single evaluation engine, not two" principle,
made real: this module is the one place that decides "given this
user/device, which policy matches, and what does it grant." The
Policy Simulator (§7) and Effective Access (§8) call this directly.
app.services.config_compiler shares `get_ordered_policies()`,
`policy_matches()`, and `get_ordered_rules_for_policy()` from this
module too (the compiler rewrite that consumes it is done, not a
follow-up), so "what the Simulator says" and "what the generated
config actually does" can never silently diverge into two
independently-written implementations.

Every evaluation function returns a plain, JSON-serializable trace
alongside its decision -- a list of {step, description, matched}
dicts recording each check in order. This isn't a debugging
afterthought bolted on top; it's the actual mechanism the Simulator
(§7) displays as "Evaluation Trace", so the trace and the decision are
generated by the exact same code path, never two separate passes that
could disagree with each other.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

from sqlalchemy.orm import Session

from ..models.command_rule import CommandRule
from ..models.command_set import CommandSet
from ..models.device import NetworkDevice
from ..models.policy import Policy
from ..models.policy_command_set import PolicyCommandSet
from ..models.user import TacacsUser


@dataclass
class TraceStep:
    step: str
    description: str
    matched: bool | None  # None = informational, not a pass/fail check

    def to_dict(self) -> dict:
        return {"step": self.step, "description": self.description, "matched": self.matched}


@dataclass
class EvaluationResult:
    matched_policy: Policy | None
    priv_lvl: int | None
    command_decision: str | None  # "permit" | "deny" | None (no command was evaluated)
    trace: list[TraceStep] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "matched_policy_id": str(self.matched_policy.id) if self.matched_policy else None,
            "matched_policy_name": self.matched_policy.name if self.matched_policy else None,
            "priv_lvl": self.priv_lvl,
            "command_decision": self.command_decision,
            "trace": [s.to_dict() for s in self.trace],
        }


def get_ordered_policies(db: Session) -> list[Policy]:
    """
    Every enabled policy, in the exact order evaluation walks them:
    ascending priority, ties broken by creation order. Shared by every
    consumer of this module (and, in a follow-up increment, the config
    compiler too) specifically so "the order the Simulator evaluated
    in" and "the order a future compiled ruleset evaluates in" are
    guaranteed to be the same query, not two hand-written ORDER BY
    clauses that could quietly drift apart.
    """
    return (
        db.query(Policy)
        .filter(Policy.enabled.is_(True))
        .order_by(Policy.priority.asc(), Policy.created_at.asc())
        .all()
    )


def policy_matches(
    policy: Policy,
    *,
    group_id=None,
    device_id=None,
    device_group_id=None,
) -> tuple[bool, list[TraceStep]]:
    """
    Whether `policy` matches this specific combination of
    group/device/device-group -- a null condition field on the policy
    means "matches anything" for that dimension (see app/models/policy.py's
    docstring for which condition fields exist in this increment).
    Returns (matched, trace) rather than just a bool: every check is
    recorded regardless of outcome, so a non-match still explains
    exactly which condition ruled it out.
    """
    trace: list[TraceStep] = []

    if policy.condition_group_id is not None:
        ok = group_id is not None and policy.condition_group_id == group_id
        trace.append(TraceStep(
            "condition_group",
            f"Policy requires group condition ({policy.condition_group_id}) -- request group is {group_id}",
            ok,
        ))
        if not ok:
            return False, trace

    if policy.condition_device_id is not None:
        ok = device_id is not None and policy.condition_device_id == device_id
        trace.append(TraceStep(
            "condition_device",
            f"Policy requires device condition ({policy.condition_device_id}) -- request device is {device_id}",
            ok,
        ))
        if not ok:
            return False, trace

    if policy.condition_device_group_id is not None:
        ok = device_group_id is not None and policy.condition_device_group_id == device_group_id
        trace.append(TraceStep(
            "condition_device_group",
            f"Policy requires device-group condition ({policy.condition_device_group_id}) -- request device group is {device_group_id}",
            ok,
        ))
        if not ok:
            return False, trace

    trace.append(TraceStep("all_conditions", f"All conditions on policy '{policy.name}' matched.", True))
    return True, trace


def get_command_sets_for_policy(db: Session, policy: Policy) -> list[CommandSet]:
    """Every enabled CommandSet a policy references, in
    PolicyCommandSet.order. A disabled CommandSet is skipped here --
    see app/models/command_set.py's docstring for why: `enabled` gates
    the whole set at once without touching every policy that
    references it."""
    joins = (
        db.query(PolicyCommandSet)
        .filter(PolicyCommandSet.policy_id == policy.id)
        .order_by(PolicyCommandSet.order.asc())
        .all()
    )
    command_sets = []
    for j in joins:
        cs = db.query(CommandSet).filter(CommandSet.id == j.command_set_id, CommandSet.enabled.is_(True)).first()
        if cs is not None:
            command_sets.append(cs)
    return command_sets


def get_ordered_rules_for_policy(db: Session, policy: Policy) -> list[CommandRule]:
    """
    Every rule from every enabled CommandSet `policy` references,
    flattened and ordered deny-first (the same deny-overrides
    principle established in Phase 5/7, now spanning multiple named
    sets instead of one policy's own inline list). Shared by
    evaluate_command (below -- finds the first match for ONE
    hypothetical command) and app.services.config_compiler (emits
    ALL of them into the generated tac_plus-ng script) so the two can
    never independently drift on ordering -- this is the "single
    evaluation engine" principle applied to rule ordering specifically,
    not just to the top-level policy-matching decision.
    """
    command_sets = get_command_sets_for_policy(db, policy)
    all_rules: list[CommandRule] = []
    for cs in command_sets:
        rules = db.query(CommandRule).filter(CommandRule.command_set_id == cs.id).order_by(CommandRule.order.asc()).all()
        all_rules.extend(rules)
    deny_rules = [r for r in all_rules if r.action == "deny"]
    permit_rules = [r for r in all_rules if r.action == "permit"]
    return deny_rules + permit_rules


def evaluate_command(db: Session, policy: Policy, command: str | None) -> tuple[str | None, list[TraceStep]]:
    """
    Deny-first evaluation of `command` against every rule from every
    CommandSet `policy` references (see get_ordered_rules_for_policy).
    Returns (None, trace) if no command was supplied at all -- session
    establishment (login) doesn't need a command decision, only a
    privilege level.
    """
    trace: list[TraceStep] = []
    if command is None:
        trace.append(TraceStep("command", "No command supplied -- evaluating session establishment only.", None))
        return None, trace

    command_sets = get_command_sets_for_policy(db, policy)
    if not command_sets:
        trace.append(TraceStep(
            "command_sets", f"Policy '{policy.name}' references no enabled command sets.", None
        ))
        trace.append(TraceStep(
            "default_action", f"Falling through to default_action: {policy.default_action}.", None
        ))
        return policy.default_action, trace

    all_rules = get_ordered_rules_for_policy(db, policy)
    for cs in command_sets:
        cs_rule_count = sum(1 for r in all_rules if r.command_set_id == cs.id)
        trace.append(TraceStep(
            "command_set", f"Checking command set '{cs.name}' ({cs_rule_count} rule(s)).", None
        ))

    for rule in all_rules:
        try:
            is_match = re.search(rule.command_pattern, command) is not None
        except re.error:
            trace.append(TraceStep(
                "rule_error", f"Rule pattern '{rule.command_pattern}' is not a valid regex -- skipped.", False
            ))
            continue
        trace.append(TraceStep(
            "rule_match",
            f"'{command}' {'matches' if is_match else 'does not match'} pattern '{rule.command_pattern}' ({rule.action}).",
            is_match,
        ))
        if is_match:
            return rule.action, trace

    trace.append(TraceStep(
        "default_action", f"No rule matched -- falling through to default_action: {policy.default_action}.", None
    ))
    return policy.default_action, trace


def evaluate(
    db: Session,
    *,
    user: TacacsUser | None = None,
    device: NetworkDevice | None = None,
    command: str | None = None,
    source_ip: str | None = None,
) -> EvaluationResult:
    """
    The main entry point: given a (possibly hypothetical) user and
    device, walks every enabled policy in priority order and returns
    the first full match, its granted privilege level, and -- if a
    command was supplied -- the permit/deny decision for that specific
    command. Returns a deny-everything result with an explanatory
    trace if no policy matches at all, matching this project's
    consistent "unmatched means denied, not silently permitted"
    default established since Phase 5.

    Per-policy CONDITION matching now has two paths, chosen per policy
    by app.services.condition_engine.has_condition_tree(): a policy
    migrated to the new condition-tree model (pasted spec) is
    evaluated by that engine, using the full RequestContext including
    `source_ip`; an un-migrated policy still uses the original
    legacy flat-field check below, completely unchanged -- migrating
    is an explicit, separate action (see condition_engine.
    migrate_legacy_policy), never automatic, so an existing policy's
    behavior never silently changes underneath it.
    """
    trace: list[TraceStep] = []

    group_id = user.group_id if user else None
    device_id = device.id if device else None
    device_group_id = device.device_group_id if device else None

    trace.append(TraceStep(
        "request",
        f"user={user.username if user else '(none)'}, "
        f"device={device.name if device else '(none)'}, "
        f"source_ip={source_ip or '(none)'}, "
        f"command={repr(command) if command else '(none)'}",
        None,
    ))

    policies = get_ordered_policies(db)
    trace.append(TraceStep(
        "policy_count",
        f"{len(policies)} enabled polic{'y' if len(policies) == 1 else 'ies'} to evaluate, in priority order.",
        None,
    ))

    # Local import avoids a circular import at module load time --
    # condition_engine imports TraceStep from this module.
    from . import condition_engine

    for policy in policies:
        trace.append(TraceStep("evaluating_policy", f"Evaluating policy '{policy.name}' (priority {policy.priority}).", None))

        if condition_engine.has_condition_tree(db, policy):
            trace.append(TraceStep("condition_model", "Using condition-tree evaluation (this policy has been migrated).", None))
            context = condition_engine.RequestContext(user=user, device=device, source_ip=source_ip)
            matched, match_trace = condition_engine.evaluate_policy_condition_tree(db, policy, context)
        else:
            matched, match_trace = policy_matches(
                policy, group_id=group_id, device_id=device_id, device_group_id=device_group_id
            )
        trace.extend(match_trace)
        if not matched:
            continue

        command_decision, command_trace = evaluate_command(db, policy, command)
        trace.extend(command_trace)
        return EvaluationResult(
            matched_policy=policy,
            priv_lvl=policy.default_priv_lvl,
            command_decision=command_decision,
            trace=trace,
        )

    trace.append(TraceStep("no_match", "No enabled policy matched this request -- denying by default.", False))
    return EvaluationResult(matched_policy=None, priv_lvl=None, command_decision="deny", trace=trace)
