"""
installer.bootstrap_config
============================
Writes the very first /opt/aaa-platform/generated/tac_plus-ng.conf so
the daemon can actually be started and health-checked at the end of
Phase 1, rather than leaving it uninstalled-but-unrunnable.

Syntax below was confirmed against real upstream sample configs
(tac_plus-ng/sample/*.cfg in the event-driven-servers repository) --
the nested `id = spawnd { ... }` / `id = tac_plus-ng { ... }` block
structure, named `log <name> { destination = ... }` targets referenced
by `access log = <name>` / `authorization log = <name>` /
`accounting log = <name>`, and `background = no` to keep the master
process in the foreground (required for systemd Type=simple).

This file intentionally defines NO `host { }` (device) or `profile { }`
(authorization policy) blocks -- those are generated from PostgreSQL by
the configuration compiler that Phase 2 (Network Devices) and Phase 5
(Authorization) introduce. With no hosts defined, no NAS can
successfully authenticate yet, but the daemon builds, starts, binds
TCP/49, and is reloadable -- which is what Phase 1 needs to prove the
full build -> install -> run -> health-check pipeline end-to-end
without faking policy functionality that doesn't exist yet (spec
section 61).
"""
from __future__ import annotations

from pathlib import Path

from . import utils

GENERATED_CONF_PATH = Path("/opt/aaa-platform/generated/tac_plus-ng.conf")
LOG_DIR = Path("/var/log/aaa-platform")

# Must match app.services.config_compiler.ACCOUNTING_FIELD_SEPARATOR
# exactly (see that module's comment for why "::" was chosen). Kept as
# a separate duplicated constant rather than a shared import, for the
# same reason the whole preamble text below is duplicated rather than
# imported -- this installer module runs before the app package is
# even necessarily on disk yet.
ACCOUNTING_FIELD_SEPARATOR = "::"

BOOTSTRAP_TEMPLATE = """\
# Generated by the AAA Management Platform installer.
# DO NOT hand-edit: this file is overwritten by the configuration
# compiler (Database -> Configuration compiler -> Candidate -> Apply).
# See spec sections 13-15. This bootstrap revision defines no devices
# or authorization policy yet; it exists only to bring the daemon up
# for health checking during initial installation.

id = spawnd {{
    background = no
    listen = {{ port = 49 }}
    # Hardcoded to the standard TACACS+ port (matching
    # app.platform_settings.DEFAULTS["tacacs_port"]) rather than reading
    # a configurable setting: this is the very first config ever
    # written, before the admin can have logged in to change anything
    # via Settings yet. Every config generated afterward
    # (app.services.config_compiler.compile_candidate) reads the real,
    # current tacacs_port setting -- if the admin changes it later, the
    # normal Apply flow picks it up correctly. This bootstrap default
    # never needs to.
    spawn = {{
        instances min = 1
        instances max = 10
    }}
}}

id = tac_plus-ng {{
    log accesslog {{ destination = {log_dir}/tac_plus-ng-access.log }}
    log authorlog {{ destination = {log_dir}/tac_plus-ng-authorization.log }}
    log acctlog {{
        destination = {log_dir}/tac_plus-ng-accounting.log
        accounting format = "${{nas}}{fs}${{user}}{fs}${{port}}{fs}${{nac}}{fs}${{accttype}}{fs}${{result}}{fs}${{service}}{fs}${{cmd}}"
    }}

    access log = accesslog
    authorization log = authorlog
    accounting log = acctlog

    # No `host {{ }}` blocks yet -- added by the configuration compiler
    # once Network Devices (Phase 2) exist in the database.
}}
"""


def write_bootstrap_config() -> Path:
    """
    Written as root (setup.py runs under sudo), but this file must be
    WRITABLE by the unprivileged aaa-platform service at runtime --
    that's exactly what the configuration compiler's Apply action does
    (app.services.config_compiler.apply_candidate). The parent
    directory being owned by aaa-platform does NOT make files created
    inside it inherit that ownership; a file's owner is whoever's UID
    created it, which is root here unless explicitly chowned. Caught
    by a real failed Apply: the daemon could read this file fine
    (root's default 644 permits "other" to read, which is why
    tac-plus-ng.service started successfully and the diff view worked)
    but the service couldn't write a new candidate over it.
    """
    import grp
    import os
    import pwd

    GENERATED_CONF_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = BOOTSTRAP_TEMPLATE.format(log_dir=LOG_DIR, fs=ACCOUNTING_FIELD_SEPARATOR)
    GENERATED_CONF_PATH.write_text(content, encoding="utf-8")

    uid = pwd.getpwnam("aaa-platform").pw_uid
    gid = grp.getgrnam("aaa-platform").gr_gid
    os.chown(GENERATED_CONF_PATH, uid, gid)
    GENERATED_CONF_PATH.chmod(0o640)

    utils.ok(f"Wrote bootstrap configuration to {GENERATED_CONF_PATH}")
    return GENERATED_CONF_PATH


def validate_syntax(binary_path: str, conf_path: Path = GENERATED_CONF_PATH) -> tuple[bool, str]:
    """
    tac_plus-ng's own `-P` legacy-family convention ("parse and echo,
    then exit") was seen in the *legacy* tac_plus man page, not
    independently confirmed for tac_plus-ng specifically. We try it,
    but treat a non-zero exit as informational rather than fatal here
    -- the authoritative check is still whether the systemd service
    actually reaches `active` after start
    (installer.systemd_setup.run_first_start_diagnostic).
    """
    result = utils.run([binary_path, "-P", str(conf_path)], check=False, timeout=15)
    text = (result.stdout + result.stderr).strip()
    return result.returncode == 0, text
