"""
installer.postgres_setup
==========================
Creates the local PostgreSQL role and database used as the management
plane's source of truth (spec section 16). Runs everything through the
`postgres` OS user via `sudo -u postgres psql`, using parameterized
argv (never string-built SQL passed through a shell) and a generated
high-entropy password that is written only to a root-only credentials
file, never printed or logged.
"""
from __future__ import annotations

import secrets
import string
from pathlib import Path

from . import utils

DB_NAME = "aaa_platform"
DB_USER = "aaa_platform"
CREDENTIALS_PATH = Path("/etc/aaa-platform/db_credentials.json")


def _generate_password(length: int = 32) -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _psql(sql: str) -> utils.CommandResult:
    # Identifiers (DB_NAME/DB_USER) are module constants, not user input.
    # The password is passed as a bind-safe literal built with %-escaping
    # rules for SQL string literals (single quotes doubled), which is
    # safe here because it is generated by secrets.choice from a fixed
    # alphanumeric alphabet with no quote characters possible.
    return utils.run(
        ["sudo", "-u", "postgres", "psql", "-v", "ON_ERROR_STOP=1", "-c", sql],
        check=True,
    )


def role_exists(role: str) -> bool:
    result = utils.run(
        [
            "sudo", "-u", "postgres", "psql", "-tAc",
            f"SELECT 1 FROM pg_roles WHERE rolname='{role}'",
        ],
        check=False,
    )
    return result.stdout.strip() == "1"


def database_exists(name: str) -> bool:
    result = utils.run(
        [
            "sudo", "-u", "postgres", "psql", "-tAc",
            f"SELECT 1 FROM pg_database WHERE datname='{name}'",
        ],
        check=False,
    )
    return result.stdout.strip() == "1"


def ensure_postgres_running() -> None:
    utils.run(["systemctl", "enable", "--now", "postgresql"])
    utils.ok("PostgreSQL service is enabled and running.")


def provision_database() -> dict:
    """
    Idempotent: if the role/db already exist (e.g. re-running the
    installer), reuses them and generates a fresh password only for a
    newly created role.
    """
    ensure_postgres_running()

    if CREDENTIALS_PATH.exists():
        utils.info("Existing database credentials found -- reusing them.")
        import json
        return json.loads(CREDENTIALS_PATH.read_text(encoding="utf-8"))

    password = _generate_password()

    if not role_exists(DB_USER):
        _psql(f"CREATE ROLE {DB_USER} WITH LOGIN PASSWORD '{password}'")
        utils.ok(f"Created database role '{DB_USER}'.")
    else:
        utils.warn(f"Role '{DB_USER}' already exists; leaving its password unchanged.")

    if not database_exists(DB_NAME):
        _psql(f"CREATE DATABASE {DB_NAME} OWNER {DB_USER}")
        utils.ok(f"Created database '{DB_NAME}'.")
    else:
        utils.warn(f"Database '{DB_NAME}' already exists; leaving it as-is.")

    creds = {
        "host": "127.0.0.1",
        "port": 5432,
        "database": DB_NAME,
        "username": DB_USER,
        "password": password,
    }

    CREDENTIALS_PATH.parent.mkdir(parents=True, exist_ok=True)
    CREDENTIALS_PATH.write_text(__import__("json").dumps(creds, indent=2), encoding="utf-8")
    CREDENTIALS_PATH.chmod(0o600)
    utils.ok(f"Database credentials written to {CREDENTIALS_PATH} (mode 600, root-only).")
    return creds
